export type LotteryData = {
  name: string;
};

export const lotteryData: LotteryData[] = [
  // { name: "和圣兄弟" },
  // { name: "鲍汁黄焖鸡" },
  // { name: "鱼你在一起" },
  // { name: "大鼓米线" },
  // { name: "闽南猪脚饭" },
  // { name: "酷味乐" },
  // { name: "成都你六姐" },
  // { name: "麦当劳" },
  // { name: "全州印象" },
  // { name: "传统牛肉面" },
  // { name: "杨国福麻辣烫" },
  // { name: "河南牛肉面" },
  // { name: "楚…热干面" },
  // { name: "老乡鸡" },
  // { name: "陕老顺" },
  // { name: "庆丰年" },
  // { name: "煲一世" },
  // { name: "陕西面馆" },
  // { name: "盖饭湘" },
  // { name: "正宗黄焖鸡米饭" },
  // { name: "河南面馆" },
  // { name: "KFC" },
  // { name: "黑丰抓饭" },
  // { name: "喜家德" },
  // { name: "袁记云饺" },
  // { name: "米纸越南小馆" },
  // { name: "河南优质烩面" },


  { name: "稻香情" },
  { name: "和圣兄弟" },
  { name: "花花爱花椒" },
  { name: "鲍汁黄焖鸡" },
  { name: "鱼你在一起" },
  { name: "大鼓米线" },
  { name: "即刻领鲜" },
  { name: "闽南猪脚饭" },
  { name: "酷味乐" },
  { name: "成都你六姐" },
  { name: "麦当劳" },
  { name: "全州印象" },
  { name: "食其家" },
  { name: "大米先生" },
  { name: "金大妈拌饭" },
  { name: "传统牛肉面" },
  { name: "杨国福麻辣烫" },
  { name: "董小婉" },
  { name: "鲜味牛" },
  { name: "食光到莱" },
  { name: "河南牛肉面" },
  { name: "楚…热干面" },
  { name: "老乡鸡" },
  { name: "阿正与圆圆" },
  { name: "陕老顺" },
  { name: "喆吉宝" },
  { name: "庆丰年" },
  { name: "煲一世" },
  { name: "小厨匠" },
  { name: "七口辣" },
  { name: "故乡妈妈" },
  { name: "南星汇海南鸡饭" },
  { name: "陕西面馆" },
  { name: "享德来脆皮鸡便当" },
  { name: "潮林卤" },
  { name: "盖饭湘" },
  { name: "胡同角落" },
  { name: "正宗黄焖鸡米饭" },
  { name: "黔牛得贵州米粉" },
  { name: "拌将" },
  { name: "西南东贵州牛肉粉" },
  { name: "河南面馆" },
  { name: "陈香贵" },
  { name: "KFC" },
  { name: "黑丰抓饭" },
  { name: "喜家德" },
  { name: "袁记云饺" },
  { name: "米纸越南小馆" },
  { name: "米袋鼠" },
  { name: "沂蒙煎锅" },
  { name: "河南优质烩面" },
  { name: "沙县小吃" },
  { name: "觅姐麻辣烫" },
  { name: "永利餐厅" },
];
